language: r
sudo: false
cache: packages
os: osx
script:
- R CMD install --build .
deploy:
  provider: releases
  api_key:
    secure: xxx
  file_glob: true
  file: "*.tgz"
  skip_cleanup: true
  on:
    tags: true
    repo: dyalog/rscproxy
